JK-71 -- Better Validation of extraneous fields
jikkenio/jikken pull request #144
Opened 2024-06-29 18:42 UTC by darius-jikkenio

A continuing work in progress, but I think this is something we'll want ( in its present state ) before releasing. To protect the remaining structs will require moving away from "flatten".

2024-06-30 16:37 UTC, louis-jikkenio approved these changes

2024-06-30 16:38 UTC, louis-jikkenio requested changes
We need to fix the unit tests

2024-06-30 21:00 UTC, darius-jikkenio commented
Unit tests fixed. More changes:
- BodyOrSchema removed from `UnvalidatedX` types. We now have both `body` and `bodySchema` . We do our own validation to ensure only one is specified. This allows us to deny unknown fields on more structs.

2024-07-03 12:31 UTC, louis-jikkenio approved these changes

2024-07-03 12:31 UTC, merged