JK-503 -- DateTime modifiers generation issue. Also, improve flexibility
jikkenio/jikken pull request #162
Opened 2024-08-18 15:17 UTC by darius-jikkenio

of variable parsing by using serde alias

2024-08-18 17:25 UTC, louis-jikkenio requested changes
Same minor issue is there twice.

2024-08-18 17:25 UTC, louis-jikkenio commented on src/test/file.rs
> +    pub fn apply_modifier(
Looks like this method is on the instance of the struct (&self) but we don't use self anywhere and instead pass in the variables. I'd either rely on &self and leverage the fields, or remove &self so it's "static" on the type.

2024-08-18 17:25 UTC, louis-jikkenio commented on src/test/file.rs
> +    pub fn apply_modifier(
Looks like this method is on the instance of the struct (&self) but we don't use self anywhere and instead pass in the variables. I'd either rely on &self and leverage the fields, or remove &self so it's "static" on the type.

2024-08-18 17:27 UTC, cameron-jikkenio approved these changes

2024-08-19 00:17 UTC, louis-jikkenio approved these changes

2024-08-19 00:17 UTC, merged