Add validated applicative to accumulate errors when validating tests
jikkenio/jikken pull request #60
Opened 2024-02-18 15:22 UTC by dariusSalem

2024-02-18 15:24 UTC, dariusSalem commented
![image](https://github.com/jikkenio/jikken/assets/13170987/c122741e-e869-428d-8874-b85cdcbcb582)
Richer errors

2024-02-18 15:32 UTC, dariusSalem commented
We could also , in a future commit, decorate our test output with failure details

2024-02-19 22:48 UTC, louis-jikkenio commented
> We could also , in a future commit, decorate our test output with failure details

We should already be doing this. When our executor runs it spits out errors as they happen (basically hardcoded into the execution methods), and we have a diff which spits out data discrepancies (all of them).

2024-02-19 22:52 UTC, louis-jikkenio requested changes

2024-02-19 22:52 UTC, louis-jikkenio commented on Cargo.toml
> +nonempty-collections = { version="0.1.5" }
Can we split up the cargo.toml to have a [dev-dependencies] section. We can move some of the dependencies (such as the nonempty-collections into that, as those dependencies aren't included in the release build. I'm worried about too many packages bloating the package size.

2024-02-20 19:58 UTC, louis-jikkenio approved these changes

2024-02-20 19:59 UTC, merged